/* STENCILBOX app — local-first authoring, exact recipe exchange, inspection and exports. */
(function(){'use strict';
 const E=TraceEngine,$=id=>document.getElementById(id),$$=s=>Array.from(document.querySelectorAll(s));
 const STORAGE='stencilbox.project.v1',PREFS='stencilbox.preferences.v1',SHELF='stencilbox.shelf.v1',BASELINE='stencilbox.baseline.v1';
 const names={scatter:'Scatter',grid:'Grid',honeycomb:'Honeycomb',triangles:'Facets',voronoi:'Voronoi',radial:'Orbit',waves:'Waves',weave:'Weave'};
 const descriptions={scatter:'Free-range geometry. Random shapes, safely packed.',grid:'A familiar rhythm, with just enough human disorder.',honeycomb:'A hexagonal field with connected material between cells.',triangles:'A field of triangular facets, separated by solid webs.',voronoi:'A cellular mosaic. Random seeds become irregular openings.',radial:'A little geometry in orbit. Repeating shapes on rings.',waves:'Rounded slots that follow an undulating rhythm.',weave:'Alternating slots: a woven pattern without loose islands.'};
 let settings={...E.defaults},edits={},model=null,mesh=null,inspection=null,viewer=null,view='stencil',zoom2=1,pan2=[0,0],selected=null,drag=null;
 let timer=null,saveTimer=null,toastTimer=null,history=[],future=[],lastHistoryKey='',lastHistoryTime=0,advanced=false,dirty=false,shelf=[],baseline=null,buildCount=0;
 const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const clone=x=>JSON.parse(JSON.stringify(x));const fmt=(n,d=1)=>Number(n).toFixed(d).replace(/\.0$/,'');
 function toast(text,error=false){clearTimeout(toastTimer);$('toast').textContent=text;$('toast').classList.toggle('error',error);$('toast').hidden=false;toastTimer=setTimeout(()=>$('toast').hidden=true,error?6500:3600);}
 // Copy legacy same-origin data only when a STENCILBOX entry is absent.
 // Never remove or overwrite the original TRACEFORM data.
 const legacyKeys={
  [STORAGE]:'traceform.project.v1',[PREFS]:'traceform.preferences.v1',
  [SHELF]:'traceform.shelf.v1',[BASELINE]:'traceform.baseline.v1'
 };
 function localRead(key,fallback){
  try{
   const current=localStorage.getItem(key);
   if(current!==null)return JSON.parse(current);
   const legacy=legacyKeys[key]&&localStorage.getItem(legacyKeys[key]);
   if(!legacy)return fallback;
   const value=JSON.parse(legacy);
   if(key===STORAGE&&value?.format==='traceform-project')value.format='stencilbox-project';
   localWrite(key,value);
   return value;
  }catch{return fallback;}
 }
 function localWrite(key,value){try{localStorage.setItem(key,JSON.stringify(value));return true;}catch{return false;}}
 function status(text,kind=''){const el=$('saveStatus');el.className='save-state '+kind;el.innerHTML='<i></i>'+escape(text);}
 function snapshot(){return{settings:clone(settings),edits:clone(edits)};}
 function pushHistory(key='',force=false){const now=Date.now();if(force||key!==lastHistoryKey||now-lastHistoryTime>700){history.push(snapshot());if(history.length>80)history.shift();future=[];}lastHistoryKey=key;lastHistoryTime=now;updateUndo();}
 function updateUndo(){$('undoBtn').disabled=!history.length;$('redoBtn').disabled=!future.length;}
 function restore(s){settings=E.normalize(s.settings);edits=clone(s.edits||{});selected=null;sync();build();scheduleSave();updateUndo();}
 function undo(){if(!history.length)return;future.push(snapshot());restore(history.pop());lastHistoryKey='';}
 function redo(){if(!future.length)return;history.push(snapshot());restore(future.pop());lastHistoryKey='';}
 function scheduleSave(){dirty=true;status('Unsaved changes','dirty');clearTimeout(saveTimer);saveTimer=setTimeout(()=>{status('Saving…','dirty');const data={format:'stencilbox-project',schemaVersion:1,generatorVersion:E.VERSION,units:'mm',settings,edits};if(localWrite(STORAGE,data)){dirty=false;status('Saved locally');}else status('Export JSON to save','error');},400);}
 function build(){clearTimeout(timer);timer=null;try{const t=performance.now();model=E.generate(settings,edits);settings=model.p;mesh=E.mesh(model);inspection=E.inspect(model,mesh);buildCount++;if(selected&&!model.holes.some(h=>h.id===selected))selected=null;updateStats();draw2D();updateSelection();renderChecks();if(viewer)viewer.setMesh(mesh,settings);$('busy').hidden=true;window.__stencilboxReady=true;window.__traceformReady=true;window.__lastBuildMs=Math.round(performance.now()-t);}catch(err){$('busy').hidden=true;$('stlBtn').disabled=true;status('Geometry needs attention','error');toast(err.message,true);console.error(err);}}
 function scheduleBuild(){clearTimeout(timer);$('busy').hidden=false;timer=setTimeout(build,90);}
 function flush(){if(timer)build();}
 function setSetting(key,value,source=''){try{const q=E.normalize({...settings,[key]:value});if(q[key]===settings[key])return;pushHistory('setting:'+key);settings=q;if(['seed','pattern'].includes(key)){edits={};selected=null;}sync(source);if(key==='name'||key==='notes'){if(model)model.p={...settings};scheduleSave();return;}scheduleBuild();scheduleSave();}catch(e){toast(e.message,true);sync();}}
 const sliderSpecs={openingControls:[['count','Density / target count',0,180,1,''],['openingScale','Opening size',25,160,1,'%'],['jitter','Disorder',0,100,1,'%'],['variation','Size variation',0,85,1,'%','advanced'],['roundness','Soften corners',0,70,1,'%','advanced']],transformControls:[['patternScale','Pattern scale',40,200,1,'%'],['rotation','Pattern rotation',-180,180,1,'°'],['holeRotation','Each opening rotation',-180,180,1,'°','advanced'],['stretchX','Stretch X',40,200,1,'%','advanced'],['stretchY','Stretch Y',40,200,1,'%','advanced'],['shear','Shear',-80,80,1,'%','advanced'],['offsetX','Move X',-160,160,1,'mm','advanced'],['offsetY','Move Y',-160,160,1,'mm','advanced']],physicalControls:[['thickness','Thickness',.4,8,.1,'mm'],['border','Solid border',1,30,.5,'mm'],['minWeb','Minimum connecting web',.4,12,.1,'mm'],['corner','Outer corner radius',0,40,1,'mm','advanced']],printControls:[['nozzle','Nozzle diameter',.1,2,.05,'mm'],['lineWidth','Assumed extrusion width',.1,3,.05,'mm'],['layerHeight','Assumed layer height',.05,.8,.05,'mm'],['tipWidth','Drawing tip width',.1,10,.1,'mm']]};
 function setupControls(){for(const[group,specs]of Object.entries(sliderSpecs))$(group).innerHTML=specs.map(([id,label,min,max,step,unit,adv])=>`<div class="slider-field ${adv?'advanced-only':''}" data-control="${id}"><div class="slider-top"><label for="${id}Range">${label}</label><div class="value"><input type="number" id="${id}" data-setting="${id}" min="${min}" max="${max}" step="${step}" aria-label="${label}, ${unit||'count'}"><span class="unit">${unit}</span></div></div><input type="range" id="${id}Range" data-setting="${id}" min="${min}" max="${max}" step="${step}" aria-label="${label}"></div>`).join('');
  const icon={scatter:'<circle cx="7" cy="9" r="4"/><path d="m23 2 5 9H18z"/><path d="m12 19 5-4 4 5-5 4z"/><circle cx="30" cy="22" r="3"/>',grid:'<path d="M2 3h7v7H2zm12 0h7v7h-7zm12 0h7v7h-7zM2 17h7v7H2zm12 0h7v7h-7zm12 0h7v7h-7z"/>',honeycomb:'<path d="m8 2 6 4v7l-6 4-6-4V6zm16 0 6 4v7l-6 4-6-4V6zm-8 14 6 3v7l-6 3-6-3v-7z"/>',triangles:'<path d="M2 2h12L2 13zm15 0 13 11H17zM2 17h12v10zm16 0h14L18 27z"/>',voronoi:'<path d="m2 2 10 1 2 9-12 3zm14 0 15 1-3 11-11-3zM2 18l12-3 4 12H2zm17-2 10 1 3 10H21z"/>',radial:'<circle cx="17" cy="14" r="3"/><path d="m14 0 6 0-3 8zM1 8l6-3 3 8zm2 13 2-6 7 4zm11 7 0-6 7 0zm17-7-7-2 3-6zm-1-16-5 7-4-7z"/>',waves:'<path d="m2 7 9-4m3 1 8 3m3 2 8-3M2 18l9-4m3 1 8 3m3 2 8-3" fill="none" stroke-width="4" stroke-linecap="round"/>',weave:'<path d="M2 5h9m9-3v8m6-5h8M6 17v8m9-4h8m8-4v8" fill="none" stroke-width="4" stroke-linecap="round"/>'};
  $('patternGrid').innerHTML=E.patterns.map(k=>`<button data-pattern="${k}" aria-pressed="false" title="${escape(descriptions[k])}"><svg viewBox="0 0 36 30" aria-hidden="true">${icon[k]}</svg><span>${names[k]}</span></button>`).join('');
  $$('[data-setting]').forEach(el=>{const key=el.dataset.setting,event=(el.type==='range'||el.type==='checkbox'||el.tagName==='SELECT')?'input':(key==='notes'?'input':'change');el.addEventListener(event,()=>{let val=el.type==='checkbox'?el.checked:el.type==='range'||el.type==='number'?Number(el.value):el.value;if(el.type==='number'&&el.value===''){sync();return;}setSetting(key,val,el.id);});});
  $$('[data-pattern]').forEach(btn=>btn.addEventListener('click',()=>setSetting('pattern',btn.dataset.pattern)));
 }
 function sync(source=''){for(const el of $$('[data-setting]')){if(el.id===source)continue;const val=settings[el.dataset.setting];if(el.type==='checkbox')el.checked=val;else el.value=val;}$('projectName').value=settings.name;$('recipeBadge').textContent=`${names[settings.pattern].toUpperCase()} / ${settings.seed}`;$$('[data-pattern]').forEach(el=>el.setAttribute('aria-pressed',String(el.dataset.pattern===settings.pattern)));$('patternNote').textContent=descriptions[settings.pattern];$('shapeRow').hidden=['voronoi','triangles','honeycomb','waves','weave'].includes(settings.pattern);document.querySelector('[data-control="corner"]').hidden=settings.board!=='rounded';
  // Fixed-pattern controls are hidden rather than pretending they affect the result.
  document.querySelector('[data-control="jitter"]').hidden=settings.pattern==='triangles';document.querySelector('[data-control="variation"]').hidden=settings.pattern==='triangles';
 }
 function updateStats(){$('statHoles').textContent=model.holes.length;$('statOpen').innerHTML=fmt(model.openPercent,1)+'<small>%</small>';$('statWeb').innerHTML=fmt(settings.minWeb,1)+'<small>mm</small>';$('statVolume').innerHTML=fmt(model.materialArea*settings.thickness/1000,1)+'<small>cm³</small>';$('dimensions').textContent=`${fmt(settings.width)} × ${fmt(settings.height)} × ${fmt(settings.thickness)} mm`;
  const warnings=inspection.findings.filter(f=>f.severity==='warning').length;const ok=mesh.validation.ok;$('checkLabel').textContent=!ok?'STL blocked':warnings?`Mesh verified · ${warnings} note${warnings===1?'':'s'}`:'Mesh verified';$('checksBtn').classList.toggle('warning',warnings>0||!ok);$('stlBtn').disabled=!ok;$('emptyHint').hidden=model.holes.length>0;
  const omitted=model.omitted.filter(h=>h.reason!=='hidden by you').length;let s=`${model.holes.length} usable openings · ${mesh.faces.length.toLocaleString()} triangles`;if(settings.pattern!=='scatter'&&omitted)s+=` · ${omitted} omitted for clearance`;if(settings.pattern==='scatter'&&model.holes.length<settings.count)s+=` · ${settings.count} requested`;$('geometryStatus').textContent=s;}
 function svgMarkup(m,mode='stencil',thumbnail=false){const p=m.p,plate=E.path(m.outer),compound=[plate,...m.holes.map(h=>E.path(h.poly))].join(' ');if(thumbnail)return`<g transform="translate(0 ${p.height}) scale(1 -1)"><path d="${compound}" fill="#91b760" fill-rule="evenodd"/></g>`;
  let s=`<defs><filter id="stencilShadow" x="-20%" y="-20%" width="150%" height="160%"><feDropShadow dx="0.8" dy="-1.2" stdDeviation="0.65" flood-color="#263c20" flood-opacity=".19"/></filter></defs><g transform="translate(0 ${p.height}) scale(1 -1)">`;
  if(mode==='stencil'){s+=`<path d="${compound}" fill="var(--plate)" stroke="var(--plate-edge)" stroke-width=".22" fill-rule="evenodd" filter="url(#stencilShadow)"/>`;if($('omittedToggle').checked)s+=m.omitted.slice(0,120).map(h=>`<path d="${E.path(h.poly)}" fill="none" stroke="#a6523c" stroke-width=".28" stroke-dasharray="1 1" opacity=".7"/>`).join('');s+=m.holes.map(h=>`<path data-hole="${h.id}" class="opening-target" d="${E.path(h.poly)}" fill="transparent" stroke="${h.id===selected?'#142d20':'transparent'}" stroke-width="${h.id===selected?'.6':'.2'}"><title>${escape(h.id)} · ${escape(h.type)} · drag to move</title></path>`).join('');if(selected){const h=m.holes.find(h=>h.id===selected);if(h){const b=E.bbox(h.poly),c=E.center(h.poly);s+=`<rect x="${b.x0-1}" y="${b.y0-1}" width="${b.x1-b.x0+2}" height="${b.y1-b.y0+2}" fill="none" stroke="#28492d" stroke-width=".25" stroke-dasharray="1.2 1" pointer-events="none"/><path d="M${c[0]-1.3},${c[1]}h2.6M${c[0]},${c[1]-1.3}v2.6" stroke="#28492d" stroke-width=".25" pointer-events="none"/>`;}}}
  else{s+=`<path d="${plate}" fill="#faf9f1" stroke="#b9c3ac" stroke-width=".25" filter="url(#stencilShadow)"/>`;s+=m.holes.map(h=>`<path d="${E.path(h.poly)}" fill="none" stroke="#2d493b" stroke-width=".38" stroke-linejoin="round"/>`).join('');}
  s+='</g>';const gap=5.5,txt=2.4;s+=`<g fill="none" stroke="#86927d" stroke-width=".15"><path d="M0 ${p.height+gap-1.5}v3m0-1.5h${p.width}m0-1.5v3"/><path d="M${p.width+gap-1.5} 0h3m-1.5 0v${p.height}m-1.5 0h3"/></g><g fill="#69795f" font-family="ui-monospace,monospace" font-size="${txt}"><text x="${p.width/2}" y="${p.height+gap+3.8}" text-anchor="middle">${fmt(p.width)} mm</text><text transform="translate(${p.width+gap+4},${p.height/2}) rotate(-90)" text-anchor="middle">${fmt(p.height)} mm</text></g>`;return s;}
 function draw2D(m=model){if(!m)return;const el=$('preview'),rect=$('surface').getBoundingClientRect(),w=rect.width,h=rect.height,mobile=w<550,scale=Math.max(.05,Math.min((w-(mobile?70:125))/m.p.width,(h-135)/m.p.height))*zoom2,vw=w/scale,vh=h/scale;el.setAttribute('viewBox',`${m.p.width/2-vw/2-pan2[0]} ${m.p.height/2-vh/2-pan2[1]} ${vw} ${vh}`);el.innerHTML=svgMarkup(m,view==='drawing'?'drawing':'stencil');}
 function setView(v){flush();if(v==='3d'){try{if(!viewer){viewer=new StencilViewer($('glCanvas'));viewer.setMesh(mesh,settings);}viewer.active=true;}catch(e){toast(e.message,true);return;}}else if(viewer)viewer.active=false;view=v;selected=null;$('preview').toggleAttribute('hidden',v==='3d');$('glCanvas').hidden=v!=='3d';$('isoBtn').hidden=v!=='3d';$$('[data-view]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.view===v)));$('viewLabel').textContent=v==='3d'?'TRUE THICKNESS / ORTHOGRAPHIC':v==='drawing'?'IDEAL DRAWING / OUTLINES ONLY':'TOP VIEW / DIMENSIONED GEOMETRY';$('surfaceSubtitle').textContent=v==='drawing'?'The marks your stencil can leave.':v==='3d'?'The actual mesh. Not a picture of one.':'Negative space. Positive possibilities.';$('interactionHint').textContent=v==='3d'?'Drag to orbit · Shift-drag to pan · scroll to zoom.':v==='drawing'?'Ideal outlines; pencil shape and thickness affect real marks.':'Select an opening to make it your own.';updateSelection();draw2D();if(v==='3d')requestAnimationFrame(()=>viewer.draw());}
 function fit(){if(view==='3d')viewer.fit();else{zoom2=1;pan2=[0,0];draw2D();}}
 function zoom(f){if(view==='3d')viewer.zoomBy(f);else{zoom2=Math.max(.2,Math.min(8,zoom2*f));draw2D();}}
 function point(e){const pt=$('preview').createSVGPoint();pt.x=e.clientX;pt.y=e.clientY;const v=pt.matrixTransform($('preview').getScreenCTM().inverse());return[v.x,settings.height-v.y];}
 function updateSelection(){const h=model?.holes.find(x=>x.id===selected);$('selectionPanel').hidden=!h||view!=='stencil';if(!h)return;const c=E.center(h.poly),e=edits[selected]||{};$('selectionTitle').textContent=`Opening ${h.id.slice(1)} · ${h.type}`;$('selX').value=fmt(c[0],2);$('selY').value=fmt(c[1],2);$('selRotation').value=e.rotation||0;$('selScale').value=e.scale||100;}
 function applyEdit(e){if(!selected)return;flush();const trial=clone(edits);trial[selected]=e;const next=E.generate(settings,trial),ids=new Set(next.holes.map(h=>h.id));if(!ids.has(selected)||model.holes.some(h=>!ids.has(h.id))){toast('That edit would break the border or minimum web. The opening has not moved.',true);draw2D();updateSelection();return false;}pushHistory('edit:'+selected,true);edits=trial;build();scheduleSave();return true;}
 function selectOpening(id){selected=id;draw2D();updateSelection();}
 function setupCanvas(){const svg=$('preview');svg.addEventListener('pointerdown',e=>{if(e.button===1||e.shiftKey){drag={pan:true,px:e.clientX,py:e.clientY,prev:[...pan2],scale:svg.clientWidth/svg.viewBox.baseVal.width};svg.setPointerCapture(e.pointerId);e.preventDefault();return;}if(view!=='stencil'||e.button!==0)return;const target=e.target.closest('[data-hole]');if(!target){if(e.target===svg||!e.target.dataset.hole){selected=null;draw2D();updateSelection();}return;}const id=target.dataset.hole;selectOpening(id);drag={id,start:point(e),edit:clone(edits[id]||{}),base:model.holes.find(h=>h.id===id),dx:0,dy:0};svg.setPointerCapture(e.pointerId);document.body.classList.add('dragging');e.preventDefault();});
  svg.addEventListener('pointermove',e=>{if(!drag)return;if(drag.pan){pan2=[drag.prev[0]+(e.clientX-drag.px)/drag.scale,drag.prev[1]+(e.clientY-drag.py)/drag.scale];draw2D();return;}const q=point(e);drag.dx=q[0]-drag.start[0];drag.dy=q[1]-drag.start[1];const ghost={...model,holes:model.holes.map(h=>h.id===drag.id?{...h,poly:h.poly.map(([x,y])=>[x+drag.dx,y+drag.dy])}:h)};draw2D(ghost);const c=E.center(drag.base.poly);$('selX').value=fmt(c[0]+drag.dx,2);$('selY').value=fmt(c[1]+drag.dy,2);});
  const stop=e=>{if(!drag)return;const d=drag;drag=null;document.body.classList.remove('dragging');try{svg.releasePointerCapture(e.pointerId);}catch{}if(d.pan){draw2D();return;}if(Math.hypot(d.dx,d.dy)>.05)applyEdit({...d.edit,dx:(d.edit.dx||0)+d.dx,dy:(d.edit.dy||0)+d.dy});else{draw2D();updateSelection();}};svg.addEventListener('pointerup',stop);svg.addEventListener('pointercancel',()=>{drag=null;document.body.classList.remove('dragging');draw2D();updateSelection();});svg.addEventListener('wheel',e=>{e.preventDefault();zoom(Math.exp(-e.deltaY*.0012));},{passive:false});new ResizeObserver(()=>draw2D()).observe($('surface'));
  for(const[id,field]of [['selRotation','rotation'],['selScale','scale']])$(id).addEventListener('change',()=>{const n=Number($(id).value);if(!Number.isFinite(n)||(field==='scale'&&(n<10||n>300))){updateSelection();return;}applyEdit({...edits[selected],[field]:n});});
  for(const[id,axis]of [['selX',0],['selY',1]])$(id).addEventListener('change',()=>{const h=model.holes.find(h=>h.id===selected);if(!h)return;const n=Number($(id).value);if(!Number.isFinite(n))return;const e=edits[selected]||{},c=E.center(h.poly),key=axis?'dy':'dx';applyEdit({...e,[key]:(e[key]||0)+n-c[axis]});});
 }
 function renderChecks(){$('findings').innerHTML=inspection.findings.map(f=>`<article class="finding ${f.severity}"><div class="finding-meta"><span class="severity">${f.severity==='pass'?'✓ Pass':f.severity}</span><span>Confidence: ${escape(f.confidence)}</span></div><h3>${escape(f.title)}</h3><p>${escape(f.detail)}</p></article>`).join('');$('assumptions').textContent=`Nozzle ${settings.nozzle} mm · extrusion width ${settings.lineWidth} mm · layer height ${settings.layerHeight} mm · bed ${settings.bedWidth} × ${settings.bedHeight} mm · drawing tip ${settings.tipWidth} mm. Material is unspecified. Values are editable in Advanced mode.`;}
 function download(data,name,type){const blob=data instanceof Blob?data:new Blob([data],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);}
 function filename(ext){return(settings.name.trim().replace(/[^a-z0-9_-]+/gi,'-').replace(/^-|-$/g,'').slice(0,70)||'stencilbox-stencil')+'.'+ext;}
 function project(){flush();return E.serialize(settings,edits,model,{checkSnapshot:{checkedAt:new Date().toISOString(),mesh:mesh.validation,clearances:inspection.measured,findings:inspection.findings},baseline:baseline?{name:baseline.settings.name,metrics:baseline.metrics}:null});}
 function exportJSON(){try{download(JSON.stringify(project(),null,2),filename('json'),'application/json');toast('JSON export prepared: recipe, edits, exact geometry and checks.');}catch(e){toast(e.message,true);}}
 function exportSTL(){try{flush();download(E.stl(mesh),filename('stl'),'model/stl');toast('STL exported. Open in your slicer as millimeters and inspect the layers.');}catch(e){toast(e.message,true);}}
 function ask(title,text,onConfirm){const d=$('confirmDialog');$('confirmTitle').textContent=title;$('confirmText').textContent=text;$('confirmOK').onclick=()=>{d.close();onConfirm();};$('confirmCancel').onclick=()=>d.close();d.showModal();}
 function importFile(file){if(!file)return;if(file.size>6*1024*1024){toast('The project is too large. The import limit is 6 MB.',true);return;}file.text().then(text=>{const data=JSON.parse(text),next=E.deserialize(data);ask('Open this stencil?',`Replace the current design with “${next.p.name}”? Your current design remains available through Undo.`,()=>{pushHistory('import',true);settings=next.p;edits=next.edits;selected=null;sync();build();scheduleSave();fit();toast('Project restored. Saved geometry matches the recipe exactly.');});}).catch(e=>toast('Could not open JSON: '+e.message,true));}
 function shuffle(){pushHistory('shuffle',true);const nums=new Uint32Array(1);if(window.crypto?.getRandomValues)crypto.getRandomValues(nums);else nums[0]=Math.floor(Math.random()*4294967296);settings.seed='FIELD-'+nums[0].toString(36).toUpperCase();edits={};selected=null;sync();build();scheduleSave();}
 function resetTransforms(){pushHistory('reset',true);for(const k of ['patternScale','rotation','holeRotation','stretchX','stretchY','shear','offsetX','offsetY','mirrorX','mirrorY'])settings[k]=E.defaults[k];sync();build();scheduleSave();fit();}
 function hideSelected(){if(!selected)return;pushHistory('hide',true);edits[selected]={...edits[selected],deleted:true};selected=null;build();scheduleSave();}
 function toggleControls(hide){document.body.classList.toggle('controls-collapsed',hide);$('showControlsBtn').hidden=!hide;setTimeout(()=>{draw2D();viewer?.draw();},20);}
 function setAdvanced(on){advanced=on;document.body.classList.toggle('advanced',on);$('modeBtn').textContent=on?'Advanced mode':'Easy mode';$('modeBtn').setAttribute('aria-pressed',String(on));persistPrefs();}
 function persistPrefs(){localWrite(PREFS,{advanced,theme:document.documentElement.dataset.theme});}
 function setTheme(theme){document.documentElement.dataset.theme=theme;persistPrefs();}
 function metrics(){return{holes:model.holes.length,openPercent:model.openPercent,volume:model.materialArea*settings.thickness/1000,web:settings.minWeb};}
 function renderShelf(){flush();const m=metrics();$('baselineInfo').innerHTML=baseline?`Baseline: <b>${escape(baseline.settings.name)}</b>. Current change: ${m.holes-baseline.metrics.holes>=0?'+':''}${m.holes-baseline.metrics.holes} openings · ${fmt(m.openPercent-baseline.metrics.openPercent)} percentage points open area · ${fmt(m.volume-baseline.metrics.volume)} cm³ material. <button id="clearBaselineBtn">Clear baseline</button>`:'No comparison baseline yet. Keep one to compare openings, open area and material use.';$('clearBaselineBtn')?.addEventListener('click',()=>{baseline=null;localWrite(BASELINE,null);renderShelf();});
  $('shelfGrid').innerHTML=shelf.length?shelf.map((s,i)=>{let sm;try{sm=E.generate(s.settings,s.edits);}catch{return'';}return`<article class="shelf-card"><svg viewBox="0 0 ${sm.p.width} ${sm.p.height}">${svgMarkup(sm,'stencil',true)}</svg><div><h3>${escape(s.settings.name)}</h3><p>${escape(names[s.settings.pattern])} · ${s.metrics.holes} openings<br>${fmt(s.settings.width)} × ${fmt(s.settings.height)} mm</p><button data-load-shelf="${i}">Open</button><button data-remove-shelf="${i}" class="remove-shelf" aria-label="Remove ${escape(s.settings.name)} from shelf">×</button></div></article>`;}).join(''):'<p class="micro">Your shelf is empty. Keep a design to start a collection.</p>';
  $$('[data-load-shelf]').forEach(b=>b.onclick=()=>{const s=shelf[Number(b.dataset.loadShelf)];ask('Restore this exploration?',`Open “${s.settings.name}”? Your current design remains available through Undo.`,()=>{pushHistory('shelf',true);restore(s);$('shelfDialog').close();fit();});});$$('[data-remove-shelf]').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.removeShelf);ask('Remove this shelf copy?','This only removes the selected local shelf copy, not the current project or any JSON files.',()=>{shelf.splice(i,1);localWrite(SHELF,shelf);renderShelf();});});}
 function printReport(){flush();const svg=`<svg class="report-svg" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${settings.width} ${settings.height}">${svgMarkup(model,'stencil',true)}</svg>`;const date=new Date().toLocaleString();$('printReport').innerHTML=`<header class="print-header"><div><h1>STENCILBOX / Stencil record</h1><p>${escape(settings.name)}</p></div><div>v${E.VERSION}<br>${escape(date)}<br>All dimensions in millimeters</div></header>${svg}<p class="print-note">Preview fitted to this report, not printed at actual size. The exported SVG has explicit millimeter dimensions.</p><h2>Recipe & dimensions</h2><div class="report-grid"><p>Family: <b>${escape(names[settings.pattern])}</b></p><p>Seed: <b>${escape(settings.seed)}</b></p><p>Plate: <b>${settings.width} × ${settings.height} × ${settings.thickness} mm</b></p><p>Usable openings: <b>${model.holes.length}</b></p><p>Minimum web target: <b>${settings.minWeb} mm</b></p><p>Solid border target: <b>${settings.border} mm</b></p><p>Open area: <b>${fmt(model.openPercent)}%</b></p><p>Material volume: <b>${fmt(model.materialArea*settings.thickness/1000)} cm³</b></p><p>Pattern scale / rotation: <b>${settings.patternScale}% / ${settings.rotation}°</b></p><p>Opening size / rotation: <b>${settings.openingScale}% / ${settings.holeRotation}°</b></p></div><h2>Findings & evidence</h2>${inspection.findings.map(f=>`<section class="report-finding"><h3>${escape(f.severity.toUpperCase())} · ${escape(f.title)}</h3><p>${escape(f.detail)} <em>Confidence: ${escape(f.confidence)}.</em></p></section>`).join('')}<h2>Assumptions</h2><p>${escape($('assumptions').textContent)}</p>${baseline?`<h2>Baseline comparison</h2><p>${escape(baseline.settings.name)}: ${model.holes.length-baseline.metrics.holes} opening change; ${fmt(model.openPercent-baseline.metrics.openPercent)} percentage-point change in open area.</p>`:''}${settings.notes?`<h2>Project notes</h2><p class="report-notes">${escape(settings.notes)}</p>`:''}<p class="report-foot">No physical print or drawing test has been performed. This is a geometry inspection, not a strength certification. Save the editable JSON alongside the STL. STENCILBOX · Green Shoe Garage / Field Instruments · no telemetry.</p>`;window.print();}
 function bind(){
  $('projectName').addEventListener('change',()=>setSetting('name',$('projectName').value||'Untitled stencil'));$('shuffleBtn').onclick=shuffle;$('undoBtn').onclick=undo;$('redoBtn').onclick=redo;$('saveBtn').onclick=exportJSON;$('stlBtn').onclick=exportSTL;$('openBtn').onclick=()=>$('fileInput').click();$('fileInput').onchange=()=>{importFile($('fileInput').files[0]);$('fileInput').value='';};$('svgBtn').onclick=()=>{flush();download(E.svg(model,view==='drawing'?'drawing':'cut'),filename('svg'),'image/svg+xml');toast('SVG exported with explicit millimeter dimensions.');};$('reportBtn').onclick=printReport;
  $('modeBtn').onclick=()=>setAdvanced(!advanced);$('themeBtn').onclick=()=>{const modes=['dark','light','contrast'];setTheme(modes[(modes.indexOf(document.documentElement.dataset.theme)+1)%modes.length]);};$('helpBtn').onclick=()=>$('helpDialog').showModal();$$('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());$$('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close();}}));
  $('collapseBtn').onclick=()=>toggleControls(true);$('showControlsBtn').onclick=()=>toggleControls(false);$$('[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view));$('checksBtn').onclick=()=>$('checksPanel').hidden=!$('checksPanel').hidden;$('closeChecksBtn').onclick=()=>$('checksPanel').hidden=true;$('zoomInBtn').onclick=()=>zoom(1.2);$('zoomOutBtn').onclick=()=>zoom(1/1.2);$('fitBtn').onclick=fit;$('isoBtn').onclick=()=>viewer?.iso();$('resetTransformBtn').onclick=resetTransforms;$('emptyResetBtn').onclick=resetTransforms;$('deselectBtn').onclick=()=>selectOpening(null);$('deleteHoleBtn').onclick=hideSelected;$('resetHoleBtn').onclick=()=>applyEdit({});$('omittedToggle').onchange=()=>draw2D();
  $('freshBtn').onclick=()=>ask('Start with a clean stencil?','Reset the current project to a blank plate and default settings. Your design shelf is kept. Undo restores this project.',()=>{pushHistory('fresh',true);settings={...E.defaults,count:0,name:'Untitled stencil',notes:''};edits={};selected=null;sync();build();scheduleSave();fit();});$('blankBtn').onclick=()=>ask('Clear all openings?','Keep the plate dimensions and print assumptions, but set the opening count to zero. Undo restores the pattern.',()=>{pushHistory('clear',true);settings.count=0;edits={};selected=null;sync();build();scheduleSave();});
  $('copySeedBtn').onclick=async()=>{try{if(!navigator.clipboard)throw Error('clipboard');await navigator.clipboard.writeText(settings.seed);toast('Seed copied. Save JSON to preserve all settings too.');}catch{$('seed').focus();$('seed').select();toast('Seed selected. Use ⌘/Ctrl C to copy.');}};
  $('shelfBtn').onclick=()=>{renderShelf();$('shelfDialog').showModal();};$('captureBtn').onclick=()=>{flush();if(shelf.length>=18){toast('Your shelf holds 18 designs. Export JSON or remove a shelf copy first.',true);return;}shelf.unshift({...snapshot(),metrics:metrics(),savedAt:new Date().toISOString()});if(!localWrite(SHELF,shelf))toast('Browser storage is full. Export JSON for a durable copy.',true);renderShelf();};$('baselineBtn').onclick=()=>{flush();baseline={...snapshot(),metrics:metrics()};localWrite(BASELINE,baseline);renderShelf();};
  document.addEventListener('dragover',e=>{if(e.dataTransfer.types.includes('Files'))e.preventDefault();});document.addEventListener('drop',e=>{if(e.dataTransfer.files.length){e.preventDefault();importFile(e.dataTransfer.files[0]);}});
  document.addEventListener('keydown',e=>{const typing=/INPUT|SELECT|TEXTAREA/.test(document.activeElement.tagName);if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='s'){e.preventDefault();exportJSON();return;}if(document.querySelector('dialog[open]'))return;if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='z'&&!typing){e.preventDefault();e.shiftKey?redo():undo();return;}if(typing)return;if(e.key==='Escape'){selectOpening(null);$('checksPanel').hidden=true;}if(e.key.toLowerCase()==='r'&&!e.ctrlKey&&!e.metaKey)shuffle();if(e.key==='1')setView('stencil');if(e.key==='2')setView('3d');if(e.key==='3')setView('drawing');if(e.key==='0')fit();if(e.key==='Delete'||e.key==='Backspace'){if(selected){e.preventDefault();hideSelected();}}if(selected&&['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();const d=e.shiftKey?2:.5,old=edits[selected]||{},dx=(e.key==='ArrowLeft'?-d:e.key==='ArrowRight'?d:0),dy=(e.key==='ArrowDown'?-d:e.key==='ArrowUp'?d:0);applyEdit({...old,dx:(old.dx||0)+dx,dy:(old.dy||0)+dy});}});
 }
 function init(){setupControls();let restoreError=false;const saved=localRead(STORAGE,null);if(saved){try{const d=E.deserialize(saved);settings=d.p;edits=d.edits;}catch{restoreError=true;}}const prefs=localRead(PREFS,{});advanced=prefs.advanced===true;document.body.classList.toggle('advanced',advanced);$('modeBtn').textContent=advanced?'Advanced mode':'Easy mode';$('modeBtn').setAttribute('aria-pressed',String(advanced));if(['dark','light','contrast'].includes(prefs.theme))document.documentElement.dataset.theme=prefs.theme;shelf=localRead(SHELF,[]);if(!Array.isArray(shelf))shelf=[];shelf=shelf.slice(0,18).filter(s=>{try{E.normalize(s.settings);return s.metrics&&typeof s.metrics.holes==='number';}catch{return false;}});baseline=localRead(BASELINE,null);if(baseline&&(!baseline.settings||!baseline.metrics))baseline=null;bind();setupCanvas();sync();toggleControls(matchMedia('(max-width:680px)').matches);build();if(restoreError){status('Local recovery needed','error');toast('The local autosave could not be restored. Your saved JSON files have not been changed.',true);}if(!restoreError)scheduleSave();
  // Read-only testing hooks plus explicit programmatic import. No hidden network integrations.
  window.Stencilbox=window.Traceform={engine:E,getSettings:()=>clone(settings),getModel:()=>model,getMesh:()=>mesh,getProject:project,getInspection:()=>inspection,getBuildCount:()=>buildCount,setSetting:(k,v)=>{setSetting(k,v);flush();},setView,select:selectOpening,applyEdit,undo,redo,shuffle,exportSTL,exportJSON,importProject:o=>{const d=E.deserialize(o);pushHistory('programmatic-import',true);restore({settings:d.p,edits:d.edits});}};
 }
 try{init();}catch(e){console.error(e);toast('STENCILBOX could not start: '+e.message,true);}
})();
