/* STENCILBOX 1.0.0 — deterministic stencil geometry. No network or platform APIs. */
(function(root,factory){
 const api=factory(typeof module==='object'&&module.exports?require('../vendor/earcut.js'):root.earcut);
 if(typeof module==='object'&&module.exports)module.exports=api; else root.TraceEngine=api;
})(typeof globalThis!=='undefined'?globalThis:this,function(earcut){
 'use strict';
 const VERSION='1.0.0', EPS=1e-7, PI=Math.PI;
 const patterns=['scatter','grid','honeycomb','triangles','voronoi','radial','waves','weave'];
 const shapes=['mixed','circle','triangle','square','diamond','hexagon','star','capsule'];
 const defaults={name:'A little beautiful disorder',seed:'FIELD-017',pattern:'voronoi',shape:'mixed',board:'rounded',width:160,height:120,thickness:1.6,border:6,corner:8,minWeb:2.4,count:52,openingScale:90,patternScale:100,rotation:0,holeRotation:0,stretchX:100,stretchY:100,shear:0,offsetX:0,offsetY:0,jitter:65,variation:35,roundness:10,mirrorX:false,mirrorY:false,nozzle:0.4,lineWidth:0.45,layerHeight:0.2,bedWidth:220,bedHeight:220,tipWidth:1,notes:''};
 const numeric={width:[40,320],height:[40,320],thickness:[0.4,8],border:[1,30],corner:[0,40],minWeb:[0.4,12],count:[0,180],openingScale:[25,160],patternScale:[40,200],rotation:[-180,180],holeRotation:[-180,180],stretchX:[40,200],stretchY:[40,200],shear:[-80,80],offsetX:[-160,160],offsetY:[-160,160],jitter:[0,100],variation:[0,85],roundness:[0,70],nozzle:[0.1,2],lineWidth:[0.1,3],layerHeight:[0.05,0.8],bedWidth:[40,1000],bedHeight:[40,1000],tipWidth:[0.1,10]};
 function normalize(p={}){const q={...defaults}; for(const k of Object.keys(defaults)){if(!(k in p))continue;if(k in numeric){const n=Number(p[k]);if(!Number.isFinite(n))throw Error(`Invalid ${k}: use a finite number.`);q[k]=Math.max(numeric[k][0],Math.min(numeric[k][1],n));}else if(typeof defaults[k]==='boolean')q[k]=p[k]===true;else q[k]=String(p[k]).slice(0,k==='notes'?6000:160);}q.count=Math.round(q.count);if(!patterns.includes(q.pattern))throw Error('Unknown pattern family.');if(!shapes.includes(q.shape))throw Error('Unknown opening shape.');if(!['rounded','rectangle','ellipse','hexagon'].includes(q.board))throw Error('Unknown stencil outline.');return q;}
 function rng(seed){let h=2166136261;for(let i=0;i<seed.length;i++)h=Math.imul(h^seed.charCodeAt(i),16777619);return function(){h+=0x6D2B79F5;let t=h;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return ((t^t>>>14)>>>0)/4294967296;};}
 const round=v=>Math.round(v*1e5)/1e5;
 const cross=(a,b,c)=>(b[0]-a[0])*(c[1]-a[1])-(b[1]-a[1])*(c[0]-a[0]);
 function area(p){let a=0;for(let i=0,j=p.length-1;i<p.length;j=i++)a+=p[j][0]*p[i][1]-p[i][0]*p[j][1];return a/2;}
 function clean(p){let q=[];for(const v of p){const z=[round(v[0]),round(v[1])];if(!q.length||Math.hypot(z[0]-q[q.length-1][0],z[1]-q[q.length-1][1])>EPS)q.push(z);}if(q.length>1&&Math.hypot(q[0][0]-q[q.length-1][0],q[0][1]-q[q.length-1][1])<EPS)q.pop();let change=true;while(change&&q.length>3){change=false;for(let i=0;i<q.length;i++){if(Math.abs(cross(q[(i+q.length-1)%q.length],q[i],q[(i+1)%q.length]))<EPS){q.splice(i,1);change=true;break;}}}if(area(q)<0)q.reverse();return q;}
 function bbox(poly){let x0=Infinity,y0=Infinity,x1=-Infinity,y1=-Infinity;for(const [x,y] of poly){x0=Math.min(x0,x);y0=Math.min(y0,y);x1=Math.max(x1,x);y1=Math.max(y1,y);}return{x0,y0,x1,y1};}
 function center(poly){let x=0,y=0,a=0;for(let i=0,j=poly.length-1;i<poly.length;j=i++){const k=poly[j][0]*poly[i][1]-poly[i][0]*poly[j][1];x+=(poly[j][0]+poly[i][0])*k;y+=(poly[j][1]+poly[i][1])*k;a+=k;}if(Math.abs(a)<EPS){const b=bbox(poly);return[(b.x0+b.x1)/2,(b.y0+b.y1)/2];}return[x/(3*a),y/(3*a)];}
 function inside(pt,poly){let b=false;for(let i=0,j=poly.length-1;i<poly.length;j=i++){const a=poly[i],c=poly[j];if(((a[1]>pt[1])!==(c[1]>pt[1]))&&(pt[0]<(c[0]-a[0])*(pt[1]-a[1])/(c[1]-a[1])+a[0]))b=!b;}return b;}
 function ptSeg(p,a,b){const dx=b[0]-a[0],dy=b[1]-a[1],l=dx*dx+dy*dy;if(l<EPS*EPS)return Math.hypot(p[0]-a[0],p[1]-a[1]);const t=Math.max(0,Math.min(1,((p[0]-a[0])*dx+(p[1]-a[1])*dy)/l));return Math.hypot(p[0]-a[0]-t*dx,p[1]-a[1]-t*dy);}
 function intersects(a,b,c,d){const a1=cross(a,b,c),a2=cross(a,b,d),a3=cross(c,d,a),a4=cross(c,d,b);if(a1*a2<0&&a3*a4<0)return true;return (Math.abs(a1)<EPS&&ptSeg(c,a,b)<EPS)||(Math.abs(a2)<EPS&&ptSeg(d,a,b)<EPS)||(Math.abs(a3)<EPS&&ptSeg(a,c,d)<EPS)||(Math.abs(a4)<EPS&&ptSeg(b,c,d)<EPS);}
 function segDist(a,b,c,d){if(intersects(a,b,c,d))return 0;return Math.min(ptSeg(a,c,d),ptSeg(b,c,d),ptSeg(c,a,b),ptSeg(d,a,b));}
 function boxDist(a,b){return Math.hypot(Math.max(0,a.x0-b.x1,b.x0-a.x1),Math.max(0,a.y0-b.y1,b.y0-a.y1));}
 function distance(a,b,stop=-1){let min=Infinity;for(let i=0;i<a.length;i++)for(let j=0;j<b.length;j++){min=Math.min(min,segDist(a[i],a[(i+1)%a.length],b[j],b[(j+1)%b.length]));if(min<stop)return min;}return min;}
 function simple(poly){for(let i=0;i<poly.length;i++)for(let j=i+2;j<poly.length;j++){if(i===0&&j===poly.length-1)continue;if(intersects(poly[i],poly[(i+1)%poly.length],poly[j],poly[(j+1)%poly.length]))return false;}return true;}
 function regular(n,rx,ry=rx,angle=0){return Array.from({length:n},(_,i)=>[rx*Math.cos(i*2*PI/n+angle),ry*Math.sin(i*2*PI/n+angle)]);}
 function roundedRect(w,h,r){r=Math.max(0,Math.min(r,w/2,h/2));if(r<.001)return[[0,0],[w,0],[w,h],[0,h]];let p=[];const corners=[[w-r,h-r,0],[r,h-r,PI/2],[r,r,PI],[w-r,r,3*PI/2]];for(const [x,y,a]of corners)for(let i=0;i<=12;i++)p.push([x+r*Math.cos(a+i*PI/24),y+r*Math.sin(a+i*PI/24)]);return clean(p);}
 function outerFor(p){let poly;if(p.board==='ellipse')poly=regular(128,p.width/2,p.height/2).map(([x,y])=>[x+p.width/2,y+p.height/2]);else if(p.board==='hexagon')poly=regular(6,p.width/2,p.height/(2*Math.sin(PI/3))).map(([x,y])=>[x+p.width/2,y+p.height/2]);else poly=roundedRect(p.width,p.height,p.board==='rectangle'?0:p.corner);return clean(poly);}
 function halfplane(poly,nx,ny,k){const out=[];if(poly.length<3)return out;for(let i=0,j=poly.length-1;i<poly.length;j=i++){const a=poly[j],b=poly[i],da=a[0]*nx+a[1]*ny-k,db=b[0]*nx+b[1]*ny-k;const ia=da<=1e-9,ib=db<=1e-9;if(ia!==ib){const t=da/(da-db);out.push([a[0]+t*(b[0]-a[0]),a[1]+t*(b[1]-a[1])]);}if(ib)out.push(b);}return out;}
 function inset(poly,d){let out=poly.slice();for(let i=0;i<poly.length;i++){const a=poly[i],b=poly[(i+1)%poly.length],dx=b[0]-a[0],dy=b[1]-a[1],l=Math.hypot(dx,dy);if(l<EPS)continue;out=halfplane(out,dy/l,-dx/l,(dy*a[0]-dx*a[1])/l-d);if(out.length<3)return[];}return out;}
 function soften(poly,r){if(r<.001||poly.length>16)return poly;const out=[];for(let i=0;i<poly.length;i++){const a=poly[(i+poly.length-1)%poly.length],b=poly[i],c=poly[(i+1)%poly.length];const t=r*.42,u=[b[0]+(a[0]-b[0])*t,b[1]+(a[1]-b[1])*t],v=[b[0]+(c[0]-b[0])*t,b[1]+(c[1]-b[1])*t];for(let j=0;j<=4;j++){const f=j/4,g=1-f;out.push([g*g*u[0]+2*g*f*b[0]+f*f*v[0],g*g*u[1]+2*g*f*b[1]+f*f*v[1]]);}}return out;}
 function motif(type,r){if(type==='circle')return regular(40,r);if(type==='triangle')return regular(3,r,r,PI/2);if(type==='square')return[[-r,-r],[r,-r],[r,r],[-r,r]];if(type==='diamond')return regular(4,r,r*1.35);if(type==='hexagon')return regular(6,r,r,PI/6);if(type==='star')return Array.from({length:10},(_,i)=>{const a=i*PI/5+PI/2,d=i%2?r*.47:r;return[d*Math.cos(a),d*Math.sin(a)];});if(type==='capsule')return roundedRect(r*2,r*.72,r*.36).map(([x,y])=>[x-r,y-r*.36]);return regular(6,r);}
 function rotate(poly,a,c=[0,0],sx=1,sy=1){const ca=Math.cos(a),sa=Math.sin(a);return poly.map(([x,y])=>{x=(x-c[0])*sx;y=(y-c[1])*sy;return[c[0]+x*ca-y*sa,c[1]+x*sa+y*ca];});}
 function generateBase(p){const random=rng(p.seed),W=p.width,H=p.height,b=p.border+1,w=Math.max(2,W-2*b),h=Math.max(2,H-2*b),n=p.count;let raw=[],id=0;const add=(poly,type)=>{if(poly.length>=3&&Math.abs(area(poly))>.04)raw.push({id:`h${id++}`,type,poly:clean(poly)});};if(!n)return raw;
 const typ=()=>p.shape==='mixed'?shapes[1+Math.floor(random()*(shapes.length-1))]:p.shape;
 const scale=()=>1+(random()-.5)*p.variation/100;
 const put=(x,y,r,t=typ(),a=0)=>{const poly=rotate(motif(t,r*scale()),a+(random()-.5)*p.jitter/100*PI);add(poly.map(([u,v])=>[x+u,y+v]),t);};
 const nx=Math.max(1,Math.round(Math.sqrt(n*w/h))),ny=Math.max(1,Math.ceil(n/nx)),dx=w/nx,dy=h/ny;
 if(p.pattern==='scatter'){
  // A bounded, oversupplied candidate stream; the final packer enforces the requested gap.
  const r=Math.sqrt(w*h/n)*.32;
  for(let i=0;i<n*18;i++)put(b+random()*w,b+random()*h,r,typ(),random()*2*PI);
 } else if(p.pattern==='voronoi'){
  const sites=[];for(let i=0;i<n;i++){const col=i%nx,row=Math.floor(i/nx),j=p.jitter/100;sites.push([b+(col+.5+(random()-.5)*j*.94)*dx,b+(row+.5+(random()-.5)*j*.94)*dy]);}
  const boundary=[[b,b],[W-b,b],[W-b,H-b],[b,H-b]];
  sites.forEach((s,i)=>{let poly=boundary.slice();for(let j=0;j<sites.length&&poly.length>2;j++){if(i===j)continue;const t=sites[j],vx=t[0]-s[0],vy=t[1]-s[1];poly=halfplane(poly,vx,vy,(t[0]*t[0]+t[1]*t[1]-s[0]*s[0]-s[1]*s[1])/2);}poly=inset(poly,p.minWeb*.54);if(poly.length>2){const c=center(poly);add(rotate(poly,0,c,scale(),scale()),'cell');}});
 } else if(p.pattern==='triangles'){
  const cols=Math.max(1,Math.round(Math.sqrt(n*w/(2*h)))),rows=Math.max(1,Math.ceil(n/(cols*2))),sx=w/cols,sy=h/rows;
  for(let j=0;j<rows;j++)for(let i=0;i<cols;i++){const x=b+i*sx,y=b+j*sy,A=[x,y],B=[x+sx,y],C=[x+sx,y+sy],D=[x,y+sy];const pair=random()<.5?[[A,B,C],[A,C,D]]:[[A,B,D],[B,C,D]];for(const tri of pair)add(inset(tri,p.minWeb*.57),'triangle');}
 } else if(p.pattern==='honeycomb'){
  const r=Math.sqrt(w*h/Math.max(1,n)/2.6),stepX=1.5*r,stepY=Math.sqrt(3)*r;
  for(let col=0,x=b+r;x<W-b;x+=stepX,col++)for(let y=b+r+(col%2)*stepY/2;y<H-b;y+=stepY){const j=p.jitter/100*.22;add(regular(6,Math.max(.5,r-p.minWeb*.65)*scale()).map(([u,v])=>[x+u+(random()-.5)*r*j,y+v]),'hexagon');}
 } else if(p.pattern==='radial'){
  const rings=Math.max(2,Math.round(Math.sqrt(n/4))),radius=Math.min(w,h)/2;put(W/2,H/2,radius/rings*.35);
  for(let ring=1;ring<=rings;ring++){const count=Math.max(5,Math.round(n*ring/(rings*(rings+1)/2))),rr=radius*ring/(rings+1),r=Math.min(radius/(rings+1)*.34,rr*PI/count*.64);for(let k=0;k<count;k++){const a=2*PI*k/count+(ring%2)*PI/count+(random()-.5)*p.jitter/100*.12;put(W/2+Math.cos(a)*rr,H/2+Math.sin(a)*rr,r,typ(),a);}}
 } else {
  for(let j=0;j<ny;j++)for(let i=0;i<nx;i++){let x=b+(i+.5)*dx,y=b+(j+.5)*dy;const r=Math.max(.3,Math.min(dx,dy)*.32);if(p.pattern==='waves'){y+=Math.sin(i*.8+j*.7)*dy*.22*(p.jitter/100);put(x,y,r*1.5,'capsule',Math.cos(i*.8+j*.7)*.45);}else if(p.pattern==='weave'){put(x,y,r*1.3,'capsule',(i+j)%2?PI/2:0);}else {x+=(random()-.5)*dx*p.jitter/100*.55;y+=(random()-.5)*dy*p.jitter/100*.55;put(x,y,r);}}
 }
 return raw;
 }
 function transformed(h,p,edit={}){let poly=soften(h.poly,p.roundness/100),c=center(poly);poly=rotate(poly,p.holeRotation*PI/180,c,p.openingScale/100,p.openingScale/100);
 const a=p.rotation*PI/180,ca=Math.cos(a),sa=Math.sin(a);poly=poly.map(([x,y])=>{x=(x-p.width/2)*p.stretchX/100*(p.mirrorX?-1:1);y=(y-p.height/2)*p.stretchY/100*(p.mirrorY?-1:1);x+=y*p.shear/100;return[p.width/2+p.offsetX+(x*ca-y*sa)*p.patternScale/100,p.height/2+p.offsetY+(x*sa+y*ca)*p.patternScale/100];});
 c=center(poly);poly=rotate(poly,(edit.rotation||0)*PI/180,c,(edit.scale||100)/100,(edit.scale||100)/100).map(([x,y])=>[x+(edit.dx||0),y+(edit.dy||0)]);return clean(poly);}
 const planeCache=new WeakMap();
 function placement(poly,outer,holes,p){if(poly.length<3||Math.abs(area(poly))<.05)return'too small';
 // Every supplied board outline is convex. Inward half-planes enforce an exact
 // Euclidean inset without repeatedly computing all edge-to-edge distances.
 let planes=planeCache.get(outer);if(!planes){planes=outer.map((a,i)=>{const b=outer[(i+1)%outer.length],dx=b[0]-a[0],dy=b[1]-a[1],len=Math.hypot(dx,dy),nx=-dy/len,ny=dx/len;return[nx,ny,nx*a[0]+ny*a[1]];});planeCache.set(outer,planes);}
 for(const [nx,ny,c] of planes)for(const [x,y] of poly)if(nx*x+ny*y-c<p.border-1e-4)return'border clearance';const b=bbox(poly);for(const h of holes){if(boxDist(b,h.bounds)>=p.minWeb)continue;if(inside(poly[0],h.poly)||inside(h.poly[0],poly)||distance(poly,h.poly,p.minWeb-1e-4)<p.minWeb-1e-4)return'web clearance';}return null;}
 function generate(settings,edits={}){const p=normalize(settings),outer=outerFor(p),holes=[],omitted=[],raw=generateBase(p);let attempts=0;for(const h of raw){if(p.pattern==='scatter'&&holes.length>=p.count)break;attempts++;const e=edits[h.id]||{};if(e.deleted){omitted.push({id:h.id,reason:'hidden by you',poly:transformed(h,p,e)});continue;}const poly=transformed(h,p,e);const why=placement(poly,outer,holes,p);if(why){if(p.pattern!=='scatter'||omitted.length<120)omitted.push({id:h.id,reason:why,poly});continue;}holes.push({...h,poly,bounds:bbox(poly)});}
 const materialArea=area(outer)-holes.reduce((a,h)=>a+area(h.poly),0);
 return{p,outer,holes,omitted,attempts,rawCount:raw.length,materialArea,openArea:area(outer)-materialArea,openPercent:100*(area(outer)-materialArea)/area(outer)};}
 const edgeKey=(a,b)=>a<b?`${a}:${b}`:`${b}:${a}`;
 function conform(vertices,triangles,loops){const boundaries=new Set();for(const loop of loops)for(let i=0;i<loop.length;i++)boundaries.add(edgeKey(loop[i],loop[(i+1)%loop.length]));let tris=triangles;
 for(let pass=0;pass<6;pass++){const counts=new Map();for(let i=0;i<tris.length;i+=3)for(let k=0;k<3;k++){const key=edgeKey(tris[i+k],tris[i+(k+1)%3]);counts.set(key,(counts.get(key)||0)+1);}const bad=new Set([...counts].filter(([k,v])=>v===1&&!boundaries.has(k)).map(([k])=>k));if(!bad.size)break;let changed=false,out=[];
 for(let i=0;i<tris.length;i+=3){let split=false;for(let k=0;k<3&&!split;k++){const a=tris[i+k],b=tris[i+(k+1)%3],c=tris[i+(k+2)%3];if(!bad.has(edgeKey(a,b)))continue;const A=vertices[a],B=vertices[b],dx=B[0]-A[0],dy=B[1]-A[1],ll=dx*dx+dy*dy,pts=[];for(let j=0;j<vertices.length;j++){if(j===a||j===b||j===c)continue;const t=((vertices[j][0]-A[0])*dx+(vertices[j][1]-A[1])*dy)/ll;if(t>1e-8&&t<1-1e-8&&ptSeg(vertices[j],A,B)<1e-7)pts.push([t,j]);}if(pts.length){pts.sort((u,v)=>u[0]-v[0]);const seq=[a,...pts.map(v=>v[1]),b];for(let j=0;j<seq.length-1;j++)out.push(seq[j],seq[j+1],c);changed=split=true;}}
 if(!split)out.push(tris[i],tris[i+1],tris[i+2]);}tris=out;if(!changed)break;}return tris;}
 function mesh(model){if(typeof earcut!=='function')throw Error('Triangulation engine did not load. Use the complete portable HTML file.');const rings=[model.outer,...model.holes.map(h=>h.poly.slice().reverse())],flat=[],loops=[],holes=[];let index=0;for(let r=0;r<rings.length;r++){if(r)holes.push(index);const loop=[];for(const v of rings[r]){flat.push(Math.fround(v[0]),Math.fround(v[1]));loop.push(index++);}loops.push(loop);}const xy=Array.from({length:index},(_,i)=>[flat[2*i],flat[2*i+1]]);let top=conform(xy,earcut(flat,holes,2),loops);const verts=xy.map(v=>[Math.fround(v[0]),Math.fround(v[1]),0]).concat(xy.map(v=>[Math.fround(v[0]),Math.fround(v[1]),Math.fround(model.p.thickness)]));const faces=[];for(let i=0;i<top.length;i+=3){let a=top[i],b=top[i+1],c=top[i+2];if(cross(xy[a],xy[b],xy[c])<0)[b,c]=[c,b];faces.push([a,c,b],[a+index,b+index,c+index]);}for(const loop of loops)for(let j=0;j<loop.length;j++){const a=loop[j],b=loop[(j+1)%loop.length];faces.push([a,b,b+index],[a,b+index,a+index]);}const out={vertices:verts,faces};out.validation=validateMesh(out,model.materialArea*model.p.thickness,model.holes.length);return out;}
 function normal(a,b,c){const u=b.map((x,i)=>x-a[i]),v=c.map((x,i)=>x-a[i]),n=[u[1]*v[2]-u[2]*v[1],u[2]*v[0]-u[0]*v[2],u[0]*v[1]-u[1]*v[0]],l=Math.hypot(...n);return l?n.map(x=>x/l):[0,0,0];}
 function validateMesh(m,expectedVolume,holeCount){const edges=new Map();let volume=0,degenerate=0;const used=new Set(),parents=m.vertices.map((_,i)=>i);const root=x=>{while(parents[x]!==x){parents[x]=parents[parents[x]];x=parents[x];}return x;};
 for(const f of m.faces){const[a,b,c]=f.map(i=>m.vertices[i]);if(![...a,...b,...c].every(Number.isFinite))throw Error('Non-finite mesh coordinate.');const ux=b[0]-a[0],uy=b[1]-a[1],uz=b[2]-a[2],vx=c[0]-a[0],vy=c[1]-a[1],vz=c[2]-a[2];if(Math.hypot(uy*vz-uz*vy,uz*vx-ux*vz,ux*vy-uy*vx)<1e-9)degenerate++;volume+=(a[0]*(b[1]*c[2]-b[2]*c[1])+a[1]*(b[2]*c[0]-b[0]*c[2])+a[2]*(b[0]*c[1]-b[1]*c[0]))/6;for(let i=0;i<3;i++){const u=f[i],v=f[(i+1)%3],key=edgeKey(u,v),old=edges.get(key)||[0,0];old[0]++;old[1]+=u<v?1:-1;edges.set(key,old);used.add(u);parents[root(u)]=root(v);}}
 const badEdges=[...edges.values()].filter(v=>v[0]!==2||v[1]!==0).length,components=new Set([...used].map(root)).size,volumeError=Math.abs(volume-expectedVolume)/Math.max(1,expectedVolume),euler=used.size-edges.size+m.faces.length;
 return{ok:badEdges===0&&degenerate===0&&components===1&&volume>0&&volumeError<1e-6&&euler===2-2*holeCount,badEdges,degenerate,components,volume,volumeError,euler,expectedEuler:2-2*holeCount,faces:m.faces.length};}
 function stl(m){if(!m.validation?.ok)throw Error('STL export blocked: the mesh did not pass topology checks.');const b=new ArrayBuffer(84+50*m.faces.length),v=new DataView(b);const label='STENCILBOX 1.0.0 | coordinates in millimeters | Z=0 on bed';for(let i=0;i<label.length;i++)v.setUint8(i,label.charCodeAt(i));v.setUint32(80,m.faces.length,true);let o=84;for(const f of m.faces){const pts=f.map(i=>m.vertices[i]),n=normal(...pts);for(const x of [...n,...pts.flat()]){v.setFloat32(o,x,true);o+=4;}v.setUint16(o,0,true);o+=2;}return b;}
 function measure(model){let minWeb=Infinity,minBorder=Infinity;for(let i=0;i<model.holes.length;i++){const a=model.holes[i];minBorder=Math.min(minBorder,distance(a.poly,model.outer));for(let j=i+1;j<model.holes.length;j++){const b=model.holes[j];if(boxDist(a.bounds,b.bounds)>=minWeb)continue;minWeb=Math.min(minWeb,distance(a.poly,b.poly));}}return{minWeb:Number.isFinite(minWeb)?minWeb:null,minBorder:Number.isFinite(minBorder)?minBorder:null};}
 function inspect(model,m){const p=model.p,findings=[],f=(severity,title,detail,confidence='High')=>findings.push({severity,title,detail,confidence});if(m.validation.ok)f('pass','One connected, closed mesh',`${m.faces.length.toLocaleString()} triangles; all edges paired; consistent winding; volume and topology verified.`);else f('error','Mesh validation failed','STL export is blocked. Try a different seed or smaller openings.');
 if(!model.holes.length)f('warning','No usable openings','This is a solid blank. Increase the opening count, reset transforms, or reduce opening size.');
 const measured=measure(model);f('pass','Clearance enforced',`Requested web ${p.minWeb.toFixed(2)} mm; measured ${measured.minWeb===null?'not applicable':measured.minWeb.toFixed(2)+' mm'}. Requested border ${p.border.toFixed(2)} mm; measured ${measured.minBorder===null?'not applicable':measured.minBorder.toFixed(2)+' mm'}.`);
 if(Math.min(p.border,p.minWeb)<p.lineWidth*3)f('warning','Thin supporting material',`The border or web is less than three assumed extrusion lines (${(p.lineWidth*3).toFixed(2)} mm). This is a design heuristic, not a strength test.`,'Medium');
 if(p.thickness/p.layerHeight<4)f('warning','Very few print layers',`Thickness is approximately ${(p.thickness/p.layerHeight).toFixed(1)} layers at your assumed layer height.`,'Medium');
 if(p.width>p.bedWidth||p.height>p.bedHeight)f('warning','Larger than the assumed print bed','The default flat orientation exceeds your bed dimensions. Check fit in the slicer; rotation may help.');
 const tiny=model.holes.filter(h=>Math.min(h.bounds.x1-h.bounds.x0,h.bounds.y1-h.bounds.y0)<p.tipWidth).length;if(tiny)f('warning','Some openings are narrower than the drawing tip',`${tiny} opening(s) have a bounding-box span below ${p.tipWidth} mm. Acute corners elsewhere can also limit access.`,'Medium');
 if(model.omitted.length&&p.pattern!=='scatter')f('info','Unsafe or hidden openings omitted',`${model.omitted.length} candidate(s) are not in the STL. Border and web clearance take priority over requested density.`);
 if(p.pattern==='scatter'&&model.holes.length<p.count)f('info','Packing limit reached',`${model.holes.length} of ${p.count} requested openings fit the current dimensions and clearances.`);
 f('info','Slicer review still required','No material, printer, adhesion, stiffness, or physical drawing test has been performed. Units must be interpreted as millimeters.','Not tested');return{findings,measured};}
 function serialize(p,edits,model,extras={}){return{format:'stencilbox-project',schemaVersion:1,generatorVersion:VERSION,units:'mm',savedAt:new Date().toISOString(),settings:normalize(p),edits:JSON.parse(JSON.stringify(edits)),geometry:{outer:model.outer,openings:model.holes.map(h=>({id:h.id,type:h.type,points:h.poly}))},...extras};}
 function deserialize(obj){if(!obj||!['stencilbox-project','traceform-project'].includes(obj.format)||obj.schemaVersion!==1||obj.units!=='mm')throw Error('Use a STENCILBOX or legacy TRACEFORM JSON project (schema 1, millimeters).');if(obj.generatorVersion!==VERSION)throw Error(`This file uses generator ${String(obj.generatorVersion).slice(0,20)}. Open it in the matching STENCILBOX release to preserve its exact geometry.`);const p=normalize(obj.settings),edits={};if(obj.edits&&typeof obj.edits!=='object')throw Error('Invalid opening edits.');for(const[k,v]of Object.entries(obj.edits||{})){if(!/^h\d{1,5}$/.test(k)||!v||typeof v!=='object')throw Error('Invalid opening edit identifier.');const q={};for(const field of ['dx','dy','rotation','scale'])if(field in v){const n=Number(v[field]);if(!Number.isFinite(n)||Math.abs(n)>1000||(field==='scale'&&n<=0))throw Error('Invalid opening transformation.');q[field]=n;}q.deleted=v.deleted===true;edits[k]=q;}if(Object.keys(edits).length>4000)throw Error('Too many edits.');const model=generate(p,edits);if(obj.geometry){if(JSON.stringify(obj.geometry.outer)!==JSON.stringify(model.outer)||JSON.stringify(obj.geometry.openings)!==JSON.stringify(model.holes.map(h=>({id:h.id,type:h.type,points:h.poly}))))throw Error('The saved geometry and recipe do not match. The file may be edited or damaged; no changes were applied.');}return{p,edits,model};}
 function path(poly){return poly.length?'M'+poly.map(v=>v.join(',')).join('L')+'Z':'';}
 function svg(model,kind='cut'){const W=model.p.width,H=model.p.height,d=[model.outer,...model.holes.map(h=>h.poly)].map(path).join(' '),draw=kind==='drawing'?model.holes.map(h=>`<path d="${path(h.poly)}" fill="none" stroke="#182c25" stroke-width="0.3"/>`).join(''):`<path d="${d}" fill="none" stroke="#000" stroke-width="0.1" fill-rule="evenodd"/>`;return`<svg xmlns="http://www.w3.org/2000/svg" width="${W}mm" height="${H}mm" viewBox="0 0 ${W} ${H}"><title>STENCILBOX stencil, millimeters</title><g transform="translate(0 ${H}) scale(1 -1)">${draw}</g></svg>`;}
 return{VERSION,defaults,numeric,patterns,shapes,normalize,rng,area,clean,bbox,center,inside,distance,placement,generate,mesh,validateMesh,normal,stl,measure,inspect,serialize,deserialize,path,svg,simple};
});
